#!/bin/bash

libDir=/usr/lib/hyde-cli
export PATH="$libDir:$PATH"

export is_fresh_install=true

. GLOBAL_hyde

#? One Time Set up on Terminal.
install_distro() {
    if [ "${1}" = "--fresh" ]; then export fresh=true; fi
    distro_ID=$(cat /etc/*release | grep -oP '^ID=\K[^"]+' | tr -d ' ' | tr '[:upper:]' '[:lower:]')
    
    case "${distro_ID}" in
        "fedora")
            Install_Hyde-DNF "${CloneDir}" "${GIT}"
        ;;
        "arch")
            Install_Hyde-PACMAN "${CloneDir}" "${GIT}"
        ;;
        *)
            echo "This is neither Fedora nor Arch"
            # Add the commands for other distributions here
        ;;
    esac
    set_metadata
}

# Variables
export install_packages_list="/tmp/hyde-cli-$(id -u)-temporary-apps"
export barLine="$(printf '=%.0s' $(seq 1 "$(tput cols)"))"
export cacheCtl="${HOME}/.cache/hyde-cli"
export meta_file="${cacheCtl}/hyde.meta"

is_link=false
while (("$#")); do
    case "$1" in
        -d | --dir)
            CloneDir="$2"
            shift 2
        ;;
        -l | --link)
            is_link=true
            shift 1
        ;;
        -g | --git)
            GIT="$2"
            shift 2
        ;;
        *)
    cat <<HANDLE_ERROR
Unknown option: $1
Please run: 'Hyde-install'                                Install Hyde (Defaults)

Advanced usage: [Hyde-install] --[options]
        -d|--dir /path/to/Clone/Hyde                       Clone Hyde in a Custom path then run installation.
                                                                    Default: '${HOME}/.cache/hyde/Hyde'
        -g|--git https://gitclone/repo/link/                     Remote Repository link to be cloned
                                                                    Default: 'https://github.com/prasanthrangan/hyde'
        -l|--link                                                Flag to transfer the link to a Clone Directory
                                                                    Default: 'false'
HANDLE_ERROR
            exit 1
        ;;
    esac
done

[[ -n ${CloneDir} ]] && print_prompt -y "Custom Clone Directory: ${CloneDir}"
[[ ${is_link} == true ]] && print_prompt - "Linked to Custom Clone Directory: ${CloneDir}"
[[ -n ${GIT} ]] && print_prompt -"Custom repository from: ${GIT}"

# Set default values if not provided
CloneDir=${CloneDir:-${HOME}/.cache/hyde/Hyde-Clone}
#TODO Change this to the upstream
# GIT=${GIT:-"https://github.com/prasanthrangan/hyde"}
GIT=${GIT:-"https://github.com/prasanthrangan/hyprdots"}

readonly CloneDir
readonly GIT
export CloneDir
export GIT


if cd "${CloneDir}"/Scripts; then
    print_prompt -m "[*] " -y "Using existing directory."
    if [[ ${is_link} == true ]]; then
        echo -e "Hyde-cli will make ${CloneDir} your Clone Directory By restoring the links."
        set_branch
        integrity_check 
        set_metadata
        print_prompt -y "Successfully Migrated the Clone Directory: ${CloneDir}"
    else
        install_distro
    fi
else
    install_distro --fresh
fi
