#!/bin/env bash

if [ "$(whoami)" = "root" ] || [ "$(id -u)" -eq 0 ]; then
    echo "Oh no! What have you done! Hyde-cli is design for 'user' space ONLY ...EXITING"
    exit 1
fi

export PATH=$PATH:/usr/lib/hyde-cli/

hyde_cli_version=$(cat /etc/hyde-cli/.hyde-cli.ver | head -1)

# . DEVEL
. GLOBAL-hyde
. DEVEL-hyde
. FUNCTIONS-hyde
initiate_hyde_command
#! DO NOT USE ANY BASH FORMATTER HERE that NUKES some ';' symbols  
#! +----------------------------------------------------------------|
#? Add functions below this section
#? Be careful with spaces in your Function definitions
#? Example Function:
#* |Function example() { #? Example Function. this comments supports '\n' 
#? |                       ^^^^ Use use as description and respects
#* | case $1 in
#* |      # Cases go here...
#* |      case1) #? Case description
#? |                ^^^ description for case functions
#* | #* |           commands...
#* | : <<USAGE
#* | [FUNCTION_CASE_USAGE ]
#* | --flags ? Description for flags
#* | --args  ? Desc for args
#* | --parms ? desc for parm
#* | [END]
#* | USAGE
#? | ^^^^^^ Usage block is a comment block that will be parsed by gen_completion and man  function 
#* |        ;;
#* |
#* |   esac; <== ' ; ' is also use to parse case conditions
#* |}
#! +----------------------------------------------------------------|

man() { #? Show Manual
    . "${meta_file}" 2>/dev/null || print_prompt -r "Looks like you did not run 'Hyde-install'! "
    manPage=$(
        echo -e "Hyde-cli: ${hyde_cli_version}"
    [ -d "${CloneDir}" ] && echo "Hyde Clone Directory: ${CloneDir}"
        echo -e "Usage: Hyde [Function] [options]\n"
        grep -E '^\w+ *\( *\)\s*\{ #\?' $0 | while read -r line; do
            Function=$(echo "$line" | awk 'BEGIN { FS = "[()#?]" } { print $1 }')
            desc=$(echo "$line" | awk 'BEGIN { FS = "[()#?]" } { gsub(/\\n/, "\\n\t\t\t", $5); print $5 }')
            printf " \n%-45s %s\n\n" "$(print_prompt -y "[" -w "${Function}" -y "]")" "$(print_prompt -y "﬌${desc}")"
            Parameters "${Function}"
        done
    )
    (
    [ "${clean_man}" = true ] || box_me "Manual Page"
    echo -e "${manPage}" |
        sed -e "s|\${CloneDir}|$CloneDir|g" \
            -e "s|\${HOME}|${HOME}|g" \
            -e "s|\${hydeConfDir}|${hydeConfDir}|g" \
            -e "s|\${ctlFile}|$ctlFile|g"
    barLine
    print_prompt -y "\nDescriptions with [*] can be expanded to show more information. Append [--help]"
    ) | { less || more || cat - ;} 2> /dev/null 
}

version() { #? Hyde-cli version

    cat <<EOF
       ░▒▒▒▒▒▒▒░░░
     ░░▒▒▒▒▒▒░░░░▓▓          ____________
    ░░▒▒▒▒▒░░░░░▓▓        //____________/
   ░░░▒▒▒░░░░░░▓▓     _   _ _     _ ______
   ░░░▒▒▒░░░░░▓▓▓▓▓▓ | | | | |   | |  ___/
    ░░░▒▒░░░░▓▓   ▓▓ | |_| | |__/ /| |_____
     ░░░▒▒░░▓▓   ▓▓   \__  |_____/ |______/
       ░░▒▒▓▓   ▓▓  //____/
EOF

    box_me -s "Hyde-cli version" -c 77
    barLine
    cat "${etcDir}/.hyde-cli.ver"
    barLine
    {
        . "${meta_file}" 2>/dev/null && box_me -s "Hyde version" -c 154 && barLine
        repo_info
        barLine
        inform_updates
    } || print_prompt -r "Looks like you did not run 'Hyde-install'! "
}

systeminfo() { #? System information
    print_prompt -y "**Hyde-cli version:**"
    cat "${etcDir}/.hyde-cli.ver"

    print_prompt -y "\n**Hyde repository:**"
    repo_info

    if [ -n "$HYPRLAND_INSTANCE_SIGNATURE" ]; then
     print_prompt -y "\n**Hyprland system information:** (hyprctl)"
    hyprctl systeminfo
    else
    print_prompt -y "\n**GPU:** "
    lspci -nn | grep -Ei "VGA|3d"

    print_prompt -y "\n**CPU:** "
    lscpu | awk -F': ' '/Model name/ {gsub(/^ *| *$| CPU.*/,"",$2); print $2}'

    print_prompt -y "\n**OS:** "
    cat /etc/os-release
    fi
}

control() { #? Interactive control file
    case $1 in
    Config) #? Manage restore control list 
        shift
        navigate_clone
        . Manage-Config
         make_List "${CloneDir}" --edit
    ;;
    *) Parameters "$Function" ;;
    esac;

}

branch() { #? Set preavailable Hyde branch
    repo_info
    set_branch
}

update() { #? Pull updates from Hyde repository
    trap 'rm -f "${cacheDir}/landing/update.check"' EXIT
    repo_info
    barLine
    get_aurhlpr
    print_prompt -y "Pulling Hyde repo..."
    git stash >/dev/null
    git pull
    git stash pop 2>/dev/null
    print_prompt -y "Checking Hyde CLI updates..."
    curl -sL https://raw.githubusercontent.com/kRHYME7/Hyde-cli/master/install.sh | bash
    inform_updates
}

upgrade() { #? Upgrades dots from the repository
    repo_info
    ask_confirm
    Manage-Config "upgrade"
    rename_backup "_Hyde_upgrade"
}

restore() { #? Restore dots
    navigate_clone
    case $1 in
    Config) #? Only restores dots from default '${CloneDir}/Configs'
        shift
        box_me "Restoring dots"
        repo_info
        # ask_confirm
        . Manage-Config
        make_List
        #  cat ${ctl_override}
        ask_confirm "${USER}"
        ./restore_fnt.sh
        Restore-Config --only "${HYDE_RUNTIME_DIR}/"
        set_metadata
        rename_backup "_Hyde_restore_Configs"
        Hyde reload
        ;;
    Clone) #? Restores dots from a clone repository \n ﯦ Provide ~/path/to/clone/directory
        Manage-Config "$1" "$2" && rename_backup "_Hyde_restore_Clone"
        #? Meta is added inside Clone function
        ;;

    BackUp) #? Restores dots from previous backup\n !! Files might not be complete\n ﯦ You can cherry pick a file/dir from a backup
        Manage-Config "${@}"
        ;;
    Link) #? Links a clone directory. Useful if you want to change your CloneDir
        repo_info
        set_branch
        shift
        new_CloneDir=${1}
        [[ -z "${1}" ]] && new_CloneDir=${CloneDir} && print_prompt -r "Missing /path/to/CloneDir"
        check_integrity
        print_prompt -y "\n[LINKING]:" -w "${CloneDir}"
        ask_confirm
        set_metadata "${new_CloneDir}"
        Hyde reload
        ;;
    *) Parameters "$Function" ;;
    esac;
}

backup() { #? Backing up commands
    navigate_clone
    case $1 in
    all) #? Backs up the current configuration
        Manage-Config "$1"
        ;;
    # custom)
    #     Manage-Config "$1"
    # ;;
    revert) #? Revert to a previous backup run by 'Hyde backup all'. \n ﯦ different from 'Hyde restore Backup', this command will restore the explicit backups like a snapshot
        Manage-Config "$1"
        ;;
    list) #? List the backup
        Manage-Config "list_Backup"
        ;;
    clean) #? Clear some storage by deleting old backups
        Manage-Config "$1"
        ;;
    *) Parameters "$Function" ;;
    esac;
}

sync() { #? Overwrite current dots from the user \n ﯦ see upstream for more info \n ﯦ add 'userPrefsDir=path/to/user/directory' in '${hydeConfDir}/hyde.conf' for custom user path
    source_user
    userPrefsDir=${userPrefsDir:-${HOME}/.config/hyde/user}
    [ ! -d "$userPrefsDir" ] && print_prompt "Undefined user directory, see upstream for more information" && return 1
    print_prompt -r "This will overwrite the current dots with the ones in '${userPrefsDir}'"
    ask_confirm "${USER}"
    # Find all files in the userPrefsDir, remove the directory prefix, and create hard links in $HOME
    find "$userPrefsDir" -type f | while read -r file; do
        # Remove the directory prefix from the file path
        relativePath=$(echo "$file" | sed "s|^$userPrefsDir/||")
        # Extract the directory part of the relative path
        targetDir="$HOME/$(dirname "$relativePath")"
        # Check if the target directory exists, and create it if it doesn't
        if [ ! -d "$targetDir" ]; then
            # mkdir -p "$targetDir"
            echo "$targetDir does not exist... Skipping"
            break
        fi
        # Create the hard link in $HOME
        cp -f "$file" "$HOME/$relativePath"
        print_prompt -g "[Overwrite] " -c " " "$file" -y "  " "$HOME/$relativePath"
    done
}

cache() { #? Manages Hyde's cache
    case $1 in
    reload) #? Reload wallpaper cache
        shift
        # [[ -z ${*} ]] && print_prompt -y "NOTE: Append the 'Theme-Name' to reload specific theme"
        swwwallcache.sh "${@}"
        ;;
    rebuild) #? Force rebuild cache
        read -n 1 -s -r -p "[ENTER:yes ANY:no] Force rebuild cache, proceed? " key
        [[ -z "$key" ]] || exit 0
        echo ""
        swwwallcache.sh -f
        ;;
        #          wall)
        # :
        #          ;;
    #  theme) #? Generate cache for current theme
    #     swwwallcache.sh -t
    #  ;;
    *)
        Parameters "$Function"
        ;;
    esac;
}

theme() { #? Theme commands
    # Function for managing themes
    case $1 in
    set) #? Set theme
        sel_Theme=$(ls $themeDir | fzf)

        "${scrDir}"/themeswitch.sh -s "$sel_Theme"
        ;;
    next) #? Next theme
        "${scrDir}"/themeswitch.sh -n
        ;;
    prev) #? Previous theme
        "${scrDir}"/themeswitch.sh -p
        ;;
    select) #? Theme selector
        "${scrDir}"/themeselect.sh
        ;;
    patch) #? Patch a theme from different repository.\nﯦ Invoking without args will launch a menu from Hyde-gallery DB
        shift
        navigate_clone
        if [[ -z "${*}" ]]; then
            Manage-Themes theme_patcher
        else
            ./themepatcher.sh "$@"
        fi
        ;;
    # remove) #? Removes a theme from the system !!  Unrecoverable
    # :

    # ;;
    *) Parameters "$Function" ;;

    esac;
}

wallpaper() { #? Wallpaper commands
    case $1 in
    set) #? Set /Path/to/Wallpapers as new wallpaper directory
        print_prompt -r "[deprecated] " -y "add 'wallAddCustomPath=( \"path/to/wallpapers\" \"...\" )' in '${hydeConfDir}/hyde.conf' instead"
        #! shift
        #! cd - || exit
        #! if [[ -z "${*}" ]] ; then echo "Missing /Path/to/Wallpaper: ${*}" ; exit 1 ; fi
        #! "${scrDir}"/swwwallpaper.sh -s "$1"
        ;;
    next) #? Next wallppaer
        "${scrDir}"/swwwallpaper.sh -n
        ;;
    prev) #? Previous wallpaper
        "${scrDir}"/swwwallpaper.sh -p
        ;;
    select) #? Wallpaper selector
        "${scrDir}"/swwwallselect.sh
        ;;
    # variety) #? EXPERIMENTAL! Use variety package to manage wallpapers
    #     shift
    #     /usr/lib/hyde-cli/Run-Wallpaper "${@}"
    # ;;
    *) Parameters "$Function" ;;

    esac;
}

wallbash() { #? Toggle to use wallpaper accent themes
    case $1 in
    toggle) #? Cycles wallbash [0] off [1] auto [2] dark [3] light
        "${scrDir}/wallbashtoggle.sh"
        ;;
    mode) #? [*] Set wallbash mode. [0] [1] [2] [3] \nﯦ no args spawns a menu
        shift
        num_val=${1}
        [ -z "${num_val}" ] && "${scrDir}"/wallbashtoggle.sh -m && return 0
        declare -A actionMap=(
            [0]="wallbash disabled"
            [1]="wallbash auto"
            [2]="wallbash dark mode"
            [3]="wallbash light mode"
        )
        # TgtScr="$scrDir/globalcontrol.sh"
        TgtScr="${hydeConfDir}/hyde.conf"

        if [[ -n "${actionMap[$num_val]}" ]]; then
            sed -i "/^enableWallDcol/c\enableWallDcol=${num_val:-${enableWallDcol}}" "${TgtScr}"
            . "$scrDir/globalcontrol.sh"
            notif="${actionMap[$num_val]}"
            echo "$notif"
        else
            echo "Invalid numeric value: $num_val"
            exit 0
        fi
        "${scrDir}/swwwallbash.sh" "$(readlink "${hydeThemeDir}/wall.set")"
        notify-send -a "t1" -i "~/.config/dunst/icons/hyprdots.png" "${notif}"
: <<USAGE
[WALLBASH_MODE_USAGE]
    0  ? wallbash disabled
    1  ? wallbash auto
    2  ? wallbash dark mode
    3  ? wallbash light mode
[END]
USAGE
        ;;

    # # term) #? Toggle terminal colors into some presets
    # #   Manage-Wallbash "${@}"
    # # ;;
    # # kitty) #? Toggle 'kitty'
    #     Manage-Wallbash "${@}"
    # # ;;
    # # waybar) #? Toggle 'waybar'
    #     Manage-Wallbash "${@}"
    # # ;;
    # # spotify) #? Toggle 'spotify'
    #     Manage-Wallbash "${@}"
    # # ;;
    *) Parameters "$Function" ;;
    esac;
}

waybar() { #? Waybar commands
    # case this is use to trick the parser that we are in case statement
    waybar_ctl=${HOME}/.config/waybar/config.ctl
    ACTION="notify-send -a \"Hyde\" \"Waybar Updated\" ; ${scrDir}/wbarconfgen.sh ; killall waybar 2> /dev/null ; $(which waybar) > /dev/null 2>&1 & disown "
    case $1 in
    control) #? Edit waybar control file
        ConfigCtl "${waybar_ctl}" "$ACTION"
        ;;
    reload) #? Reloads waybar
        eval "${ACTION}"
    ;;
    size) #? Set waybar size
        shift
        wbar_size=${1}
    if [ -z "${wbar_size}" ] || [[ $wbar_size =~ ^[0-9]+$ && $wbar_size -ge 1 && $wbar_size -le 100 ]]; then
        sed -i "s/^\(1|\)\([0-9]*|\)\?/1|${wbar_size}|/" "${waybar_ctl}"
        eval "${ACTION}"
    else
        print_prompt -r "Error: " "Valid scaling from 1-100"
        exit 1
    fi
    ;;
    *)
        Parameters "$Function"
        ;;
    esac;
}

sddm() { #? Sddm commands
    check_package sddm
    navigate_clone
    case $1 in
    theme) #? Select sddm theme
        sddm_bak=/etc/sddm.conf.d/kde_settings.t2.bkp
        sddm_conf=/etc/sddm.conf.d/kde_settings.conf
        sddm_theme=$(
        find "${CloneDir}/Source/arcs" -type f -name "*Sddm_*" -printf "%f\n" \
        | awk -F 'Sddm_' '{print $2}' |\
         awk -F '.tar' '{print $1}' | Fzf-Menu "${FUNCNAME[0]}"
        )
        [ -z "${sddm_theme}" ] && print_prompt -r "Operation Cancelled" && exit 0
        print_prompt -y "Setting into '${sddm_theme} theme'..."
        ask_confirm "${USER}"
        [ -f "${sddm_bak}" ] && SUPER rm "${sddm_bak}"
        SUPER tar -xzf ${CloneDir}/Source/arcs/Sddm_${sddm_theme}.tar.gz -C "/usr/share/sddm/themes/${theme}"
        SUPER touch "${sddm_conf}"
        SUPER cp "${sddm_conf}" "${sddm_bak}"
        SUPER cp /usr/share/sddm/themes/${sddm_theme}/kde_settings.conf /etc/sddm.conf.d/
        ;;
    #   set) #? Directory   Lockscreen
    # :    #  "${scrDir}"/sddmwall.sh
    # #
    #   ;;
    *) Parameters "$Function" ;;

    esac;
}

shell() { #? Shell commands

    case $1 in
    select) #? Shell selector
        shell_select
        ;;

    *)
        Parameters "$Function"
        ;;
    esac;
}

power() { #? Power Options

    case $1 in
    reset) #? Reset changes
        Manage-Power "$@"
        ;;
    save) #? [*] Save power by disabling features
        Manage-Power "$@"
: << USAGE
[POWER_SAVE_USAGE]
    --animations    ? Disable animations
    --borderangle   ? Disable border angle animation
    --blur          ? Disable blur
    --opacity       ? Disable tranparency
[END]
USAGE
        ;;
    toggle) #? Toggle ﯦ Set/unset current changes'
        Manage-Power "$@"
        ;;
    unset) #? [*] Unset specific changes
        Manage-Power "$@"
: <<USAGE
[POWER_UNSET_USAGE]
    --animations    ? Default animations
    --borderangle   ? Default border angle animation
    --blur          ? Default blur
    --opacity       ? Default tranparency
[END]
USAGE
        ;;
    game) #? Toggle game mode
        Manage-Power "$@"
        ;;
    *)
        Parameters "$Function"
        ;;
    esac;

}

code() { #! Modify Vscode Extensions
    case $1 in
    select) #? Selector for default Theme presets

        select_theme() {
            dir=$(grep "^1|" "${ThemeCtl}" | cut -d'|' -f3 | cut -d'~' -f1 | tr '[:upper:]' '[:lower:]')
            code_SubExt=$(cat ${HOME}/.vscode/extensions/"${dir}"*/package.json | jq -r '.contributes.themes[] | .label' | fzf)
            awk -v ext="${code_SubExt}" -F'|' 'BEGIN {OFS = FS} /^1\|/ {if ($3 ~ /~/) sub(/~[^|]*/, "~" ext, $3); else $3 = $3 "~" ext} 1' "$ThemeCtl" >temp && mv temp "$ThemeCtl"
            if [ "$(grep -c "workbench.colorTheme" "${confDir}"/Code/User/settings.json)" -eq 1 ]; then
                sed -i "/workbench.colorTheme/c\    \"workbench.colorTheme\": \"${code_SubExt}\"," "${confDir}"/Code/User/settings.json
            else
                sed -i "/^{/a\    \"workbench.colorTheme\": \"${code_SubExt}\"," "${confDir}"/Code/User/settings.json
            fi
        }
        if [[ ! -z "$(cat "${ThemeCtl}" | grep "^1|" | cut -d'|' -f3)" ]]; then
            select_theme
        else
            echo "No Linked Code Extension found. Would you like to add the extension MANUALLY?"
            ask_confirm
            sel_ext=$(/usr/bin/code --list-extensions | fzf)
            sed -i '/^1|/ s/[^|]*|[^|]*|[^|]*/&'"$sel_ext"'/' "$ThemeCtl"
            select_theme
        fi
        ;;
    *)
        Parameters "$Function"
        ;;
    esac;
}

show() { #? Some Hypr GUI you might want to use
    case $1 in
    # monitors) #? Manages monitors using nwg-displays
    #     Manage_Monitor
    # ;;
    binds) #? [*] Show keybind hints\n ﯦ Click to execute 
        # Keybinds_Hint #! Moved to .extra
        shift
        "${scrDir}"/keybinds_hint.sh "${*}"
: <<USAGE
[SHOW_BINDS_USAGE]
    -j   ?  Show the JSON format
    -p   ?  Show the pretty format
    -d   ?  Add custom delimiter symbol (default '>')
    -f   ?  Add custom file
    -w   ?  Custom width
    -h   ?  Display this help message
[END]
USAGE
        ;;
    emoji) #? Emoji selector
        Launch-Emoji
        ;;
    pastebin) #? [*] Pastebin manager \n ﯦ pass [only once] '--ignore=initialclass' to disable autopaste
        [[ $* == *"--ignore"* ]] && pasteIt "${*}"
        shift
        Launch-Pastebin "$@"
: <<USAGE
[SHOW_PASTEBIN_USAGE]
    c  ? cliphist list and copy selected
    d  ? cliphist list and delete selected
    w  ? cliphist wipe database
[END]
USAGE
        ;;
    glyph) #? Glyph selector
        Launch-Glyph
        ;;
    screencap) #? Use rofi to select screenshot options \n !!  kills another rofi session
        Launch-Screencap
        ;;
    *)
        Parameters "$Function"
        ;;

    esac;
}

run() { #? Executables
    case $1 in
    audio_idle) #? Inhibits idle when player state: 'Playing
    check_package systemd
    local command="${0} "${FUNCNAME[0]}" ${@} --listen"
      shift
     [ "--listen" = "$1" ] && while playerctl status | grep -q "Playing"; do sleep 5; done && exit 
     playerctl status | grep -q "Playing" && systemd-inhibit --what=idle --mode=block ${command}
    print_prompt -y "Player status: " " $(playerctl status)..."
    ;;
    events) #? Watches hyprland events and executes actions
    check_package
        shift
        verbose=0
        event_config=""
        while [ "$#" -gt 0 ]; do
            case "$1" in
            --verbose)
                export verbose=1
                shift
                ;;
            --config)
                export event_config="$2"
                shift 2
                ;;
            *)
                echo "Unknown option: $1"
                exit 1
                ;;
            esac
        done
        Hypr-Events
        ;;
    screencap) #? [*] Screenshot and screenrecord tool
        shift
        Run-Screencap "$@"
: <<USAGE
[RUN_SCREENCAP_USAGE]
    --print-all     ?  Print all outputs
    --record-focus  ?  Record focused monitor
    --print-snip    ?  Drag to manually snip an area
    --record-snip   ?  Drag to manually snip an area to screen record it
    -freeze         ?  Frozen screen, drag to manually snip an area
    --print-monitor ?  Print focused monitor
    --scan          ?  Use 'tesseract' to scan image then add to clipboard
    --stop          ?  Stop every instance of Screencap
    --reset         ?  Reinitialize screencap
[END]
USAGE
        ;;
    *)
        Parameters "$Function"
        ;;

    esac;

}

inject() { #? User/Device specific scripts that might be useful

    case $1 in
    chaotic_aur) #? Add chaotic aur
        shift
        SUPER /usr/lib/hyde-cli/Install-chaotic-aur "${@}"
        ;;
    asus_patch) #? Fixes issues for asus devices
    # Add Keys of asus repository
    SUPER pacman-key --recv-keys 8F654886F17D497FEFE3DB448B15A6B0E9A3FA35
    SUPER pacman-key --finger 8F654886F17D497FEFE3DB448B15A6B0E9A3FA35
    SUPER pacman-key --lsign-key 8F654886F17D497FEFE3DB448B15A6B0E9A3FA35
    SUPER pacman-key --finger 8F654886F17D497FEFE3DB448B15A6B0E9A3FA35

    # Add in pacman.conf
    echo -e "\n[g14]\nServer = https://arch.asus-linux.org" | SUPER tee -a /etc/pacman.conf

    check_package asusctl supergfxctl rog-control-center power-profiles-daemon

    #Check First before enabling
    service_check power-profiles-daemon.service supergfxd
    ;;
    # test)
    # service_check sddm
    # ;;
    *)
        Parameters "$Function"
        ;;
    esac;

}

reload() { #? Just reload
    if printenv HYPRLAND_INSTANCE_SIGNATURE &>/dev/null; then
        box_me "Reloading Dots"
        "$HOME/.local/share/bin/swwwallcache.sh" -t ""
        { [ -n "$hydeTheme" ] && "${scrDir}/themeswitch.sh" -s "$hydeTheme"; } || "${scrDir}/swwwallcache.sh"
    fi
}

#! +----------------------------------------------------------------|
"$@" #? Call the appropriate Function based on the first argument.  |
#! +----------------------------------------------------------------|
