#! /bin/bash

pkill -x rofi && exit

export PATH=$PATH:/usr/lib/hyprdots-ctl/

. GLOBAL

emojiData="$etcDir/emoji.db"
roFile="$etcDir/emoji.rasi"

# read hypr theme border
wind_border=$((hypr_border * 3))
elem_border=$([ $hypr_border -eq 0 ] && echo "10" || echo $((hypr_border * 2)))
r_override="window {border: ${hypr_width}px; border-radius: ${wind_border}px;} element {border-radius: ${elem_border}px;}"

# read hypr font size
fnt_override=$(gsettings get org.gnome.desktop.interface font-name | awk '{gsub(/'\''/,""); print $NF}')
fnt_override="configuration {font: \"JetBrainsMono Nerd Font ${fnt_override}\";}"

# read hypr theme icon
icon_override=$(gsettings get org.gnome.desktop.interface icon-theme | sed "s/'//g")
icon_override="configuration {icon-theme: \"${icon_override}\";}"

selection=$(awk -F '\t' '{print $1, $4, $5, $6,$2,$3 }' "$emojiData" | rofi -dmenu -multi-select -i -p "Select an emoji" -config "${roFile}" )
emoji=$(echo "$selection" | cut -d' ' -f1 )
echo "$emoji" |  sed '$d' | wl-copy
wtype -M ctrl v -m ctrl

