#! /bin/env bash

#? This Script stores all fzf menu related funtions
#? Call the functions by 'fzf-menu "functions"'
#? Functions have 'fzf_' prefix and its funtions to point to is the function name of the actual function
# TODO: Make this Intuitive
# TODO: Make the menu uniform

#? Add common variables
menu_height="--height 60%"

fzf_list_Marker_OVERWRITE() {
    fzf -m --marker ' ' \
        --prompt '[TAB] MARK to "OVERWRITE" [Esc] Back | CTRL A : mark all  | CTRL D : unmark all: ' \
        --bind 'ctrl-a:select-all,ctrl-d:deselect-all' \
        --preview "Manage-Config show_restore_list ${ctl_override}"
}

fzf_list_Marker_SYNC() {
    fzf -m --marker ' ' \
        --prompt '[TAB] MARK to "SYNCHRONIZE" [Esc] Back | CTRL A : mark all  | CTRL D : unmark all: ' \
        --bind 'ctrl-a:select-all,ctrl-d:deselect-all' \
        --preview "Manage-Config show_restore_list ${ctl_override}"
}

fzf_list_Marker_PRESERVE() {
    fzf -m --marker ' ' \
        --prompt '[TAB] MARK to "PRESERVE" [Esc] Back | CTRL A : mark all  | CTRL D : unmark all: ' \
        --bind 'ctrl-a:select-all,ctrl-d:deselect-all' \
        --preview "Manage-Config show_restore_list ${ctl_override}"
}

fzf_list_Marker_BACKUP() {
    fzf -m --marker ' ' \
        --prompt '[TAB] MARK to "BACKUP" [Esc] Back | CTRL A : mark all  | CTRL D : unmark all: ' \
        --bind 'ctrl-a:select-all,ctrl-d:deselect-all' \
        --preview "Manage-Config show_restore_list ${ctl_override}"
}

#? restore Config
fzf_menu_manage_config() {
    fzf --prompt='▶' \
        --pointer='→' \
        --marker='♡' \
        --cycle \
        --preview "Manage-Config show_restore_list ${ctl_override}" \
        --preview-window 'right:80%,border-rounded'
}

fzf_revert() {
    fzf --prompt 'List of explicit Backup, Run by Hyde backup all' \
        --preview 'lsd -a --tree --depth 4 '"$BkpDir"'/$(echo {} | awk "{print \$4}")'
}

fzf_clean() {
    fzf -m \
        --marker='X' \
        --cycle \
        --pointer='→' \
        --prompt '[TAB] Select [Esc] Exit | CTRL A : mark all | CTRL D : unmark all: ' \
        --bind 'ctrl-a:select-all,ctrl-d:deselect-all'
}

fzf_BackUp() {
    fzf \
        --prompt='Restoring from a Backup Directory.' \
        --preview 'lsd -a --tree --depth 4 '"$BkpDir"'/$(echo {} | awk "{print \$4}")' \
        ${menu_height}

}

fzf_shell_select() {
    fzf --prompt='Select default shell: ' \
        --marker='X' \
        --cycle \
        --pointer='→' \
        --disabled \
        --preview 'Fzf-Preview /usr/share/hyde-cli/shell_{}.png' \
        --preview-window 'right:80%,border-rounded'
}

#? Theme patch Menu
fzf_theme_menu() {
    fzf \
        --cycle \
        --preview 'Manage-Themes preview_theme {}' \
        -m \
        --marker ' ' \
        --pointer='→' \
        --prompt '[TAB] Select [Esc] Exit | CTRL A : mark all | CTRL D : unmark all: ' \
        --bind 'ctrl-a:select-all,ctrl-d:deselect-all' \
        --preview-window 'right:60%,border-rounded'

}

fzf_sddm() {

    fzf --prompt='Select SDDM theme: ' \
        --marker='X' \
        --cycle \
        --pointer='→' \
        --disabled \
        --preview 'Fzf-Preview /usr/share/hyde-cli/sddm_{}.png' \
        --preview-window 'right:80%,border-rounded'
}

eval "$(declare -F | sed -e 's/-f /-fx /')"
"fzf_${*}"
