#!/bin/bash

export PATH=${PATH}:/usr/lib/hyprdots-ctl/

handle_error() { 
cat << HANDLE_ERROR 
${1}
=======================================================================================
Please run:
           'Hyprdots-install'                                 Install Hyprdots (default)
For advanced usage see options below
        --clone= /path/to/Clone/Hyprdots                      Clone Hyprdots in a Custom path then run installation.
                                                                Default: '${HOME}/Hyprdots'
        --git https://gitclone/link/                          Repository link to be cloned
                                                                Default: 'https://github.com/prasanthrangan/hyprdots'
        --link                                                Flag to transfer the link to a Clone Directory
                                                                    Default: 'false'
HANDLE_ERROR
  exit 1 
 }

#Handles Transition
ConfDir="${XDG_CONFIG_HOME:-$HOME/.config}"
hyprdotsDir="${ConfDir}/hyprdots"
ScrDir="${hyprdotsDir}/scripts"
wallbashDir="${hyprdotsDir}/wallbash"

[[ ! -d ${hyprdotsDir} ]] && ScrDir="${HOME}/.config/hypr/scripts"  && wallbashDir="${HOME}/.config/hypr/wallbash"  && echo -e  "You are using an older version of Hyprdots! Please see upstream to adjust your configuration."


! source "${ScrDir}/globalcontrol.sh" 2> /dev/null && handle_error "Failed to source ${ScrDir}/globalcontrol.sh"
[[ -z "${CloneDir// }" ]] && handle_error "Cannot find Hyprdots Clone Directory"
[[ ! -f "${CloneDir}/Scripts/global_fn.sh" ]] && handle_error "${CloneDir}/Scripts/global_fn.sh does not exist"

ScriptDir="${CloneDir}/Scripts"
BkpDir="${ConfDir}/cfg_backups"
cacheDir="${HOME}/.cache/hyprdots"
cacheCtl="${HOME}/.cache/hyprdots-ctl"
etcDir="/etc/hyprdots-ctl"
ctlDir="${ConfDir}/hyprdots-ctl"

make_dir=(
  "${ScriptDir}"
  "${BkpDir}"
  "${cacheDir}"
  "${cacheCtl}"
  "${etcDir}"
  "${ctlDir}"
)
  for dir in "${make_dir[@]}"; do
    if [[ ! -d "${dir}" ]]; then
      mkdir -p "${dir}"
      echo "Hyprdots-ctl created a directory: ${dir}"
    fi
  done

if [ "$(ls -A "$BkpDir")" ]; then
  last_bak=$(ls -td -- $BkpDir/* | head -n 1 )
fi