#!/bin/bash

export PATH=$PATH:/usr/lib/hyprdots-ctl/

handle_error() { 
cat << HANDLE_ERROR 
Please run:
           'Hyprdots-install'                                 Install Hyprdots (default)
For advanced usage see options below
        --clone= /path/to/Clone/Hyprdots                      Clone Hyprdots in a Custom path then run installation.
                                                                Default: '${HOME}/Hyprdots'

        --git https://gitclone/link/                          Repository link to be cloned
                                                                Default: 'https://github.com/prasanthrangan/hyprdots'
HANDLE_ERROR
  exit 1 
 }

! source ${HOME}/.config/hypr/scripts/globalcontrol.sh 2> /dev/null && handle_error "Failed to source globalcontrol.sh"
[[ -z "${CloneDir// }" ]] && handle_error "Cannot find Hyprdots Directory"
[ ! -f "$CloneDir/Scripts/global_fn.sh" ] && handle_error "${ConfDir}/Scripts/global_fn.sh does not exist"

ScrDir="$ConfDir/hypr/scripts"
ScriptDir="$CloneDir/Scripts"
BkpDir="$ConfDir/cfg_backups"
cacheDir="$HOME/.cache/hyprdots"
cacheCtl="$HOME/.cache/hyprdots-ctl"
etcDir="/etc/hyprdots-ctl"
ctlDir="$ConfDir/hyprdots-ctl"


barLine() { printf '=%.0s' $(seq 1 "$(tput cols)") ; }

make_dir=(
  "$ScrDir"
  "$ScriptDir"
  "$BkpDir"
  "$cacheDir"
  "$cacheCtl"
  "$etcDir"
  "$ctlDir"
)
  for dir in "${make_dir[@]}"; do
    if [ ! -d "$dir" ]; then
      mkdir -p "$dir"
      echo "Hyprdots-ctl created a directory: $dir"
    fi
  done

if [ "$(ls -A "$BkpDir")" ]; then
  last_bak=$(ls -td -- $BkpDir/* | head -n 1 )
fi

rename_backup() {
bak=$(ls -td -- "$BkpDir"/* | head -n 1 )
if [[ "$last_bak" != $bak ]]; then
mv "$bak" "$bak-$1"
fi
}


print_prompt() {
  while (( "$#" )); do
    case "$1" in
      -r) echo -ne "\e[31m$2\e[0m" ;;  # Red
      -g) echo -ne "\e[32m$2\e[0m" ;;  # Green
      -y) echo -ne "\e[33m$2\e[0m" ;;  # Yellow
      -b) echo -ne "\e[34m$2\e[0m" ;;  # Blue
      -m) echo -ne "\e[35m$2\e[0m" ;;  # Magenta
      -c) echo -ne "\e[36m$2\e[0m" ;;  # Cyan
      -w) echo -ne "\e[37m$2\e[0m" ;;  # White
      -n) echo -ne "\e[96m$2\e[0m" ;;  # Neon
      *) echo "Invalid option: $1" ;;
    esac
    shift 2
  done
  echo ""
}

box_me() {
  local s="Hyprdots: $*"
  tput setaf 3
  echo " ═${s//?/═}"
  echo "║$s ║"
  echo " ═${s//?/═}"
  tput sgr0
}

ask_confirm() {
  local key=$1
  while true; do
    if [ -z "$key" ]; then
    read -n 1 -s -r -p "[ENTER: continue ANY: exit]" key ; [[ -z "$key" ]] && break || exit 0
    else
      read -p "Please type '$(print_prompt -m "$key")' to continue: " answer 
      if [[ "$answer" == "$key" ]]; then
        break
      else
        print_prompt -r "Invalid input, please try again."
      fi
    fi
  done
}

case_help() {
  OPTION="$1"
  sed -n "/case \${$OPTION} in/,/esac/p" "${0}" | grep '#?' | awk -F') #?' '{gsub(/ #?/, "", $1); gsub(/?/, "", $2); printf "%-30s %s\n", $1, $2}'
}

pkg_installed()
{
    local PkgIn=$1

    if pacman -Qi $PkgIn &> /dev/null
    then
        #echo "${PkgIn} is already installed..."
        return 0
    else
        #echo "${PkgIn} is not installed..."
        return 1
    fi
}

CHECK () {
    local Pkg_Dep=$(for PkgIn in "$@"; do ! pkg_installed $PkgIn && echo "$PkgIn"; done)

if [[ -n "${Pkg_Dep}" ]]; then echo -e "$0 Dependencies:\n$Pkg_Dep"
    notify-send -a "${0}" "Dependencies: '${Pkg_Dep}' Please run in the terminal first..."
    ask_confirm
    if [[ -z "${ans}" ]]; then get_aurhlpr 
    $"aurhlpr" -S $Pkg_Dep
    else echo "Skipping installation of packages" ;exit 1
    fi
fi
}


do_contain() {
    local etc_file="$1"
    local conf_file="$2"
    local tag_line=$(grep -i "Hyprdots-ctl tag:" "${etc_file}")

    if [[ ! -f "${conf_file}" ]] || grep -qF "${tag_line}" "${conf_file}" ; then
        cp "${etc_file}" "${conf_file}"
        # echo "Copied $etc_file to ${conf_file} because it contained '${tag_line}'"
    else :
        # echo "Did not copy ${etc_file} to ${conf_file} because it did not contain '${tag_line}'"
        print_prompt -r "Warning:" -m "File was changed: ${conf_file}" -w "\n Delete file to recieve updates" 
    fi
}