#! /bin/env bash

#* $TOSKIP variable is used to skip certain KEYWORDS
TOSKIP=(
    "[CONFIRM]"
    "NOTE:"
    "N/A"
)

#* [source_section] accepts the section name of the DB
#* this sources the certain block with the section name header
#* Blocks are stored to ' sourceFile="${HYDE_RUNTIME_DIR}/${section}.meta" ' 
source_section() {
    local section="$1"
    local dbFile="$2"
    sourceFile="${HYDE_RUNTIME_DIR}/${section}.meta"
    grep -Pzo "(?s)\[$section\][^\[]*" "${dbFile}" | grep -Eva '^\['"$section"'\]|^$' | awk '/:#/ {exit} 1' | tr -d '\0' >"${sourceFile}"
    # cat "${sourceFile}"
    . "${sourceFile}"
}



# Define the function
#* [select_exec] Accepts an array[@]
#* Usefull for level 1 selection without preview
#* Might be useless use selector instead
select_exec() {
    local selected_opt="$(printf '%s\n' "${@:1}" | awk -F '?' '{printf "%-40s %s\n", $1, $2}' |
        fzf --cycle --tac \
            --prompt=': ' \
            --pointer='→' |
        cut -d ' ' -f1)"
    eval "$(printf '%s\n' "${@:1}" | grep "${selected_opt}" | awk -F '?' '{print $3}')"
}

# select_version() {
#     local selected_opt="$(printf '%s\n' "${@:1}" | awk -F '?' '{printf "%-40s %s\n", $1, $2}' |
#         fzf --cycle \
#             --prompt=': ' \
#             --pointer='→' |
#         cut -d ' ' -f1)"
#     echo "${selected_opt}"
    
# }

#* [selector] accepts atleast 2 vars,
#* 1st: Any functions that is named menu_${menuOption}_select ; $menuOption should be the first string 
#* 2nd: Section of the Package Group
#* 3rd: Default Package group
#* 4th: Section name will be turned to $sectionName override it here( space turns to _ by default)
selector() {
    local menuOpt="${1}"
    shift
    export fzfOvrMultiNum=""
    if [[ $1 == "--only" ]]; then
        shift
        fzfOvrMultiNum="1"
    fi
    export section="$1"
    local default="$2"
    local sectionName="${3:-${section// /_}}"
    source_section "${section}" "${metaFile}"
    "menu_${menuOpt}_select" "${sectionName}" "${default}"
}


eval "$(declare -F | sed -e 's/-f /-fx /')"
# "${@}"
