#!/bin/bash

#? One Time Set up on Terminal. 

export PATH=$PATH:/usr/lib/hyprdots-ctl/

CloneDir="$HOME/Hyprdots" 
# echo -e "$(tput setaf 5)\nHyprdots-ctl Cannot find the Hyprdots Directory, Will proceed to default installation!$(tput sgr0)"
# read -n 1 -s -r -p "[ENTER:yes ANY:no] Proceed? " key ; [[ -z "$key" ]] || exit 0 


if [ -d "$CloneDir" ] && cd "$CloneDir"; then
    echo -e "\n\nDirectory $CloneDir already exists. Using existing directory.\n"
    echo -e "Hyprdots-ctl will make $CloneDir your Clone Directory By restoring the links."
    read -n 1 -s -r -p "[ENTER:yes ANY:no] Proceed? " key ; [[ -z "$key" ]] || exit 0 
    echo "[ok]"
git reset --hard HEAD  && git clean -fd  && git pull  || true
    cd "$CloneDir"/Scripts || exit 0
    ./restore_lnk.sh

else 

distro_ID=$(cat /etc/*release | grep -oP '^ID=\K[^"]+' | tr -d ' ' | tr '[:upper:]' '[:lower:]')

case "$distro_ID" in
  "fedora")
    echo "This is Fedora"
     Install_Hyprdots-DNF "$CloneDir"
    ;;
  "arch")
     Install_Hyprdots-PACMAN "$CloneDir"
    ;;
  *)
    echo "This is neither Fedora nor Arch"
    # Add the commands for other distributions here
    ;;
esac


fi