#!/bin/bash



read -n 1 -s -r -p "[ENTER:yes ANY:no] Hyprdots not detected! This will run the installation. " key
  [[ -z "$key" ]] || exit 0 

cat << CHAOS


Would you like to add Chaotic AUR to your mirror list? 
Chaotic AUR provides prebuilt and precompiled packages, 
which can make installing packages from Arch faster."

Type "Sure" to add achaotic AUR to your mirror list. 
[ENTER] to skip the installation.

CHAOS

read add_chaotic
if [ "$add_chaotic" != "n" ] && [ "$add_chaotic" != "N" ]; then
sudo /usr/lib/hyprdots-ctl/Install_ChaoticAUR --install
fi
  


  git clone --depth 1 https://github.com/prasanthrangan/hyprdots $HOME/Hyprdots
  cd $HOME/Hyprdots/Scripts
  ./install.sh