#!/bin/bash
#  ____              _                         _
# | __ )  ___   ___ | | ___ __ ___   __ _ _ __| | _____
# |  _ \ / _ \ / _ \| |/ / '_ ` _ \ / _` | '__| |/ / __|
# | |_) | (_) | (_) |   <| | | | | | (_| | |  |   <\__ \
# |____/ \___/ \___/|_|\_\_| |_| |_|\__,_|_|  |_|\_\___/
#
# -----------------------------------------------------

# Define the path to the bookmarks file

pkill -x rofi && exit

rofi_pos

check_package wtype

BOOKMARKS_PATH=""

if [[ $BROWSER == "brave" ]]; then
	BOOKMARKS_PATH="$HOME/.config/BraveSoftware/Brave-Browser/Default/Bookmarks"
elif [[ $BROWSER == "vivaldi" || $BROWSER == "chromium" ]]; then
	BOOKMARKS_PATH="$HOME/.config/$BROWSER/Default/Bookmarks"
elif [[ $BROWSER == "google-chrome-stable" ]]; then
	BOOKMARKS_PATH="$HOME/.config/google/Default/Bookmarks"
else
	notify-send -a "Browser not supported" -t 2000
	exit 1
fi

selected=$(grep '"url":' "$BOOKMARKS_PATH" | awk '{print $2}' | sed 's/"//g' | rofi -dmenu -i -theme-str "entry { placeholder: \"Select Bookmark...\";} ${pos} ${r_override}" -theme-str "${fnt_override}" -config "${roFile}")

if [ "$selected" ]; then
	xdg-open "$selected"
fi
