#!/bin/bash

file=/tmp/$(date "+%Y%m%d-%H%M%S")_screenshot.png
grim -g "$(slurp)" - | swappy -f - -o "$file" &&
yad --title="Upload OK?" --text="Upload OK?" --image="dialog-question" --default-cancel &&
curl -F"file=@$file" https://0x0.st | wl-copy -n &&
notify-send --expire-time=2000 "Uploaded, URL Copied!." "$(wl-paste)"
