#! /bin/env bash

sddm() {
    if ! pkg_installed sddm; then echo -e "\033[0;33m[WARNING]\033[0m sddm is not installed..." ; exit  0 ;fi
    
    echo -e "\033[0;32m[DISPLAYMANAGER]\033[0m detected // sddm"
    if [ ! -d /etc/sddm.conf.d ] ; then
        SUPER mkdir -p /etc/sddm.conf.d
    fi
    
    # if [ ! -f /etc/sddm.conf.d/kde_settings.t2.bkp ] ; then
    echo -e "\033[0;32m[DISPLAYMANAGER]\033[0m configuring sddm..."
    echo -e "Select sddm theme:\n1) Candy\n2) Corners"
    read -p "Enter option number : " sddmopt
    
    case $sddmopt in
        1) sddmtheme="Candy";;
        *) sddmtheme="Corners";;
    esac
    
    SUPER tar -xzf ${CloneDir}/Source/arcs/Sddm_${sddmtheme}.tar.gz -C /usr/share/sddm/themes/
    SUPER touch /etc/sddm.conf.d/kde_settings.conf
    SUPER cp /etc/sddm.conf.d/kde_settings.conf /etc/sddm.conf.d/kde_settings.t2.bkp
    SUPER cp /usr/share/sddm/themes/${sddmtheme}/kde_settings.conf /etc/sddm.conf.d/
    # else
    #     echo -e "\033[0;33m[SKIP]\033[0m sddm is already configured..."
    # fi
    
    if [ ! -f /usr/share/sddm/faces/${USER}.face.icon ] && [ -f ${CloneDir}/Source/misc/${USER}.face.icon ] ; then
        SUPER cp ${CloneDir}/Source/misc/${USER}.face.icon /usr/share/sddm/faces/
        echo -e "\033[0;32m[DISPLAYMANAGER]\033[0m avatar set for ${USER}..."
    fi
    
}




"${@}"