#!/bin/env bash

. /usr/lib/hyprdots-ctl/GLOBAL

CHECK variety

varietyDir=$ConfDir/variety/hyprdots
varietyScript="${varietyDir}/scripts/hyprdots_wallpaper"

# Pass arguments here
if [[ -n ${*} ]]; then
    print_prompt -y "Command:" -w "${@}"
    variety --profile="${varietyDir}" --set-option=set_wallpaper_script "${varietyScript}" "${@}"
    exit 0
fi

# This will loop forever
if [[ -e "${varietyScript}" ]] ; then
    print_prompt -y "Starting as Daemon"
    [[ -z "${*}" ]] && print_prompt -y "'Hyprdots wallpaper variety [ -h | --help ]' for options"
    variety --profile="${varietyDir}" --set-option=set_wallpaper_script "${varietyScript}"
    exit 0
fi

# One time Setup
nohup variety --profile="${varietyDir}" --set-option=set_wallpaper_script "${varietyScript}" &

while [[ ! -e "${varietyDir}" ]]; do sleep 1 ; done

notify-send -a "Hyprdots: Variety Setup" "Please setup your profile" -e
sed -n '/^### startVARIETY ###$/,/^### endVARIETY ###$/{//!p}' "${0}" > "${varietyScript}"
chmod +x "${varietyScript}" && exec ${0} "${@}"

exit 0

### startVARIETY ###
#! /bin/bash

WP="${1}"
ConfDir="${XDG_CONFIG_HOME:-$HOME/.config}"
hyprdotsDir="${ConfDir}/hyprdots"
ScrDir="${hyprdotsDir}/scripts"
source "${ScrDir}/globalcontrol.sh"

CurrThemeDir=$(awk -F '|' '/^1/ {print $NF}' ${ThemeCtl} | xargs -d '\n' dirname)
THEME=$(awk -F '|' '/^1/ {print $2}' "${ThemeCtl}")
varBase="A_VARIETY_WALLPAPER_${THEME}.png"
VARIETY="$(eval realpath "${CurrThemeDir}")/${varBase}"

cp -f "${WP}" "${VARIETY}"

PID=$(pgrep swww-daemon)
if [[ -n ${PID} ]] && [[ -e ${VARIETY} ]]; then
    find ~/.cache/hyprdots/ -type f -name "${varBase}*" -delete && Hyprdots wallpaper set "${VARIETY}"
    notify-send -a "Hyprdots" "${VARIETY}" -i "${VARIETY}" -e
fi

### endVARIETY ###
